[Icon Theme]
Name=Spectrum Folders Light
 
Comment=Color-changing Breeze folders
 
DisplayDepth=32
 
Inherits=breeze

Example=folder
 
FollowsColorScheme=true
 
DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
 
KDE-Extensions=.svg

Directories=places/16,places/22,places/32,places/64,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/64

#MIMETYPES; needed for generic folders

#16x16 - Fixed size - For small file type icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed
MinSize=16

#22x22 - Fixed size - For small file type icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[mimetypes/22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

#32x32 - Scalable - For file type icons >!!!ONLY!!!< - Scalable to the following sizes: 64x64 (default), 32x32, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[mimetypes/32]
Size=32
Context=MimeTypes
Type=Scalable
MinSize=32
MaxSize=48

#64x64 - Scalable - For file type icons >!!!ONLY!!!< - Scalable to the following sizes: 64x64 (default), 32x32, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[mimetypes/64]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=64
MaxSize=256



#PLACES; e.g. documents, images, music

#16x16 - Fixed size - For small folder icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

#16x16@2x - Fixed size - For small folder icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[places/16@2x]
Size=16
Scale=2
Context=Places
Type=Fixed
MinSize=16

#22x22 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. KMail trash icon - WRONG_ICON_USAGE_BY_APP - Monochrome
[places/22]
Size=22
Context=Places
Type=Fixed

#22x22@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. KMail trash icon - WRONG_ICON_USAGE_BY_APP - Monochrome
[places/22@2x]
Size=22
Scale=2
Context=Places
Type=Fixed

#32x32 - Scalable - For folder icons >!!!ONLY!!!< - Scalable to the following sizes: 64x64 (default), 32x32, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[places/32]
Size=32
Context=Places
Type=Scalable
MinSize=24
MaxSize=48

#64x64 - Scalable - For folder icons >!!!ONLY!!!< - Scalable to the following sizes: 64x64 (default), 32x32, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[places/64]
Size=64
Context=Places
Type=Scalable
MinSize=64
MaxSize=256
